# Add 'feature' label if feat branch is used
feature:
  - head-branch: ['feat']

# Add 'bug' label if hotfix or fix branch is used
fix:
  - head-branch: ['hotfix', 'fix']

# Add 'test' label if test branch is used
test:
  - head-branch: ['test']

# Add 'release' label if main branch is used
release:
  - base-branch: 'main'

# Add 'dependencies' label to any changes in package files
dependencies:
  - changed-files:
      - any-glob-to-any-file: ['package.json', 'pnpm-lock.yaml']

# Add 'approved' label when PR is approved
approved:
  - any: ['**/*']
    condition: approved
